(fix): Added support for new keys of INFO statement return value in nightly build
StarlaneStudios/Surrealist pull request #64
Opened 2023-06-13 14:16 UTC by bibaswan-bhawal

Added support for the new key names returned by the INFO FOR statement whilst maintaining backwards compatibility with previous versions of surreal.

fixes #62

2023-06-13 14:27 UTC, macjuul requested changes
Looking good!

2023-06-13 14:27 UTC, macjuul commented on package-lock.json
Is it possible to omit this file from the commit? You may have used `npm install` instead of `pnpm install` (Surrealist uses pnpm)

2023-06-13 14:29 UTC, bibaswan-bhawal commented on package-lock.json
ya give me a sec

2023-06-13 14:45 UTC, bibaswan-bhawal commented
Also as a side note, what formater do you use? Every time I open up the project my formater formats every file i open so my commits include files that haven't changed. If you have a standard formater Ill switch to that moving forward. If not, I recommend Prettier.

2023-06-13 14:55 UTC, merged

2023-06-16 15:29 UTC, ntorrey commented
Thanks @bibaswan-bhawal and @macjuul ! Looking forward to the updated version of Surrealist!